### PR TITLE
Add main.c main.cpp main.py

### PR DESCRIPTION
**Pull request by Wenqing-hub**

### CODE REVIEW

**Comment by qinweijian7** [comment]
LGTM

**Comment by Wenqing-hub** [comment]
`code`

**Comment by Wenqing-hub** [comment]
code

**Comment by Wenqing-hub** [comment]
- [x] 1
- [ ] 2

**Comment by Wenqing-hub** [comment]
1. 

> 1211

**Comment by Hangjie22Coder** [comment]
```
111

**Comment by Wanghangjie8** [comment]
[666]:(888)

**Comment by Wenqing-hub** [comment]
[hub](https://github.com/wenqing-hub)

**Comment by Wenqing-hub** [comment]
```mermaid
flowchart LR
A(Linux) 
A -->B(linux系统及服务器管理)
A -->C(数据库及自动化运维)
```

**Comment by Wanghangjie8** [comment]
'commit'

**Comment by Hangjie22Coder** [comment]
`commit`

**Pull request merged**
